from setuptools import setup

setup(
	name='UniPELT',
	version='',
	packages=['transformers', 'transformers.data', 'transformers.data.metrics', 'transformers.data.datasets',
	          'transformers.data.processors', 'transformers.utils', 'transformers.models', 'transformers.models.t5',
	          'transformers.models.dpr', 'transformers.models.led', 'transformers.models.mt5',
	          'transformers.models.rag', 'transformers.models.vit', 'transformers.models.xlm',
	          'transformers.models.auto', 'transformers.models.bart', 'transformers.models.bert',
	          'transformers.models.ctrl', 'transformers.models.fsmt', 'transformers.models.gpt2',
	          'transformers.models.mmbt', 'transformers.models.ibert', 'transformers.models.mbart',
	          'transformers.models.mpnet', 'transformers.models.tapas', 'transformers.models.xlnet',
	          'transformers.models.albert', 'transformers.models.funnel', 'transformers.models.lxmert',
	          'transformers.models.marian', 'transformers.models.openai', 'transformers.models.barthez',
	          'transformers.models.deberta', 'transformers.models.electra', 'transformers.models.gpt_neo',
	          'transformers.models.herbert', 'transformers.models.m2m_100', 'transformers.models.pegasus',
	          'transformers.models.phobert', 'transformers.models.roberta', 'transformers.models.bertweet',
	          'transformers.models.big_bird', 'transformers.models.convbert', 'transformers.models.dialogpt',
	          'transformers.models.flaubert', 'transformers.models.layoutlm', 'transformers.models.reformer',
	          'transformers.models.wav2vec2', 'transformers.models.camembert', 'transformers.models.retribert',
	          'transformers.models.blenderbot', 'transformers.models.deberta_v2', 'transformers.models.distilbert',
	          'transformers.models.longformer', 'transformers.models.mobilebert', 'transformers.models.prophetnet',
	          'transformers.models.transfo_xl', 'transformers.models.squeezebert', 'transformers.models.xlm_roberta',
	          'transformers.models.bert_japanese', 'transformers.models.speech_to_text',
	          'transformers.models.xlm_prophetnet', 'transformers.models.bert_generation',
	          'transformers.models.encoder_decoder', 'transformers.models.blenderbot_small', 'transformers.adapters',
	          'transformers.adapters.models', 'transformers.commands', 'transformers.benchmark',
	          'transformers.pipelines', 'transformers.sagemaker'],
	url='',
	license='',
	author='ml-ctauchmann',
	author_email='',
	description=''
)
